version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/backend_blog
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres_user
    working_dir: /backend
    ports: 
      - '5432:5432'
    expose:
      - '5432'
    restart: always
    networks:
      - blognetwork

  backend:
    build: backend
    image: rails-backend
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3001:3000"
    working_dir: /backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    restart: always
    networks:
      - blognetwork

  frontend:
    build: frontend
    image: react-frontend
    command: sh -c "npm install && npm start"
    ports:
      - "3002:3000"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
      - db
    restart: always
    networks:
      - blognetwork

networks:
  blognetwork:
    driver: bridge